on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: "willsoto/actions/.github/workflows/node-ci.yml@v2.0.2"
    secrets:
      GitHubToken: ${{ secrets.GH_TOKEN }}
      NPMToken: ${{ secrets.NPM_TOKEN }}
